macOS Build fixes + enable building on Apple Silicon macs (#3247)
* macOS: Update/upgrade detection of sha256sum to use shasum if available

This is because shasum is always there, whereas the others may not exist
on e.g. latest homebrew.

* macOS make_osx script fixup to support newer homebrew openssl package

It ceased to work on newer homebrew since openssl@1.1 no longer exists.
We will just allow openssl3 to be used with python3, which is ok.

* macOS make_osx: Don't use deterministic requirements -hw and -binaries

They no longer work for OSX -- so instead we simply use non-pinned
versions in contrib/requirements.

Since OSX build is not deterministic anyway, using the pinned versions
has no advantage (and potentially only disadvantages). This is fine for
OSX build only.

* OSX: remove defunct/unused file: requirements-binaries-elcapitan.txt

This is no longer ever used and never needed.

* OSX build: Download libusb-1.0.dylib that is a fat binary

Has "universal" arch support for: x86_64 and arm64

* OSX build: Newer brew needs to install autoconf-archive

If found, we also check that it's installed and/or install it

* macos build: Require libiconv in brew

* OSX: Fixes for building zbar with homebrew

Fixed both for make_osx and standalone contrib/make_zbar

diff --git a/contrib/make_zbar b/contrib/make_zbar
--- a/contrib/make_zbar
+++ b/contrib/make_zbar
@@ -35,7 +35,9 @@ elif [ "$BUILD_TYPE" = "darwin" ] ; then
         brew info libiconv | grep -E '^Installed' > /dev/null || fail "libiconv missing -- please install it with: brew install libiconv"
         brew_pfx=$(brew --prefix)
         [ -n "${brew_pfx}" ] || fail "Cannot determine path to HomeBrew libiconv"
-        EXTRA_FLAGS+=" --with-libiconv-prefix=${brew_pfx}"
+        iconv_dir="${brew_pfx}/opt/libiconv"
+        [ -d "${iconv_dir}/lib" ] || fail "Libiconv seems to be missing from brew"
+        EXTRA_FLAGS+=" --with-libiconv-prefix=${iconv_dir}"
     else
         fail "Could not determine if using MacPots or HomeBrew -- please install one of them and then install libiconv"
     fi
diff --git a/contrib/osx/make_osx b/contrib/osx/make_osx
--- a/contrib/osx/make_osx
+++ b/contrib/osx/make_osx
@@ -76,7 +76,11 @@ have_brew=`which brew`
 have_macports=`which port`
 if [ -n "$have_brew" ]; then
     info "Ensuring build prerequisites are installed via brew"
-    for a in autoconf automake coreutils gettext libtool openssl@1.1 readline sqlite3 xz zlib swig ; do
+    brew info openssl@1.1 > /dev/null 2>&1 && OPENSSL="openssl@1.1" || OPENSSL=openssl
+    brew info autoconf-archive > /dev/null 2>&1 && AUTOCONF_ARCHIVE="autoconf-archive" || AUTOCONF_ARCHIVE=""
+    brew info libiconv > /dev/null 2>&1 && LIBICONV="libiconv" || LIBICONV=""
+    for a in autoconf $AUTOCONF_ARCHIVE automake coreutils gettext $LIBICONV libtool $OPENSSL pkgconf readline sqlite3 \
+             xz zlib swig ; do
         brew list $a > /dev/null 2>&1
         if [ "$?" != "0" ]; then
             info "Installing $a"
@@ -197,10 +201,10 @@ info "Making locale..."
 python3 ./contrib/make_locale || fail "Failed to make locale..."
 
 info "Downloading libusb..."
-curl -L https://github.com/cculianu/Electron-Cash-Build-Tools/releases/download/v1.0/libusb-1.0.21.el_capitan.bottle.tar.gz | \
-    tar xz --directory $BUILDDIR || fail "Could not download libusb"
-verify_hash $BUILDDIR/libusb/1.0.21/lib/libusb-1.0.dylib d147e7382dfa676d93e8b17d160d50f68e4b01f58f3647c90a8899a7a0519ca3  # this exits on failure
-cp -fp $BUILDDIR/libusb/1.0.21/lib/libusb-1.0.dylib contrib/osx || fail "Could not copy libusb"
+curl -L https://github.com/cculianu/Electron-Cash-Build-Tools/releases/download/v1.0/libusb-1.0.dylib.gz | \
+    gunzip -c > $BUILDDIR/libusb-1.0.dylib || fail "Could not download libusb"
+verify_hash $BUILDDIR/libusb-1.0.dylib c8735d48dd6d01681303b157e794c9d4cdc16f14e15ee0751afdf6020db03ae1  # this exits on failure
+mv -vf $BUILDDIR/libusb-1.0.dylib contrib/osx/. || fail "Could not move libusb into place"
 
 # Build ZBar
 contrib/make_zbar && mv -vf electroncash/libzbar.0.dylib contrib/osx/. || fail "Could not build ZBar"
@@ -230,11 +234,14 @@ contrib/make_zlib && contrib/make_libevent && contrib/make_openssl && contrib/ma
 
 info "Installing requirements..."
 python3 -m pip install -r ./contrib/deterministic-build/requirements.txt --user || fail "Could not install requirements"
-python3 -m pip install -r ./contrib/deterministic-build/requirements-binaries.txt --user || fail "Could not install binary requirements"
+#python3 -m pip install -r ./contrib/deterministic-build/requirements-binaries.txt --user || fail "Could not install binary requirements"
+# Note that on macos the deterministic requirements-binaries now fails, fall back to simple requirements. We are not deterministic anyway on this platform so it's fine.
+python3 -m pip install -r ./contrib/requirements/requirements-binaries-osx-sonoma.txt --user || fail "Could not install binary requirements"
 
 info "Installing hardware wallet requirements..."
-python3 -m pip install -r ./contrib/deterministic-build/requirements-hw.txt --user || \
-fail "Could not install hardware wallet requirements"
+#python3 -m pip install -r ./contrib/deterministic-build/requirements-hw.txt --user || fail "Could not install hardware wallet requirements"
+# Note that on macos the deterministic requirements-hw now fails, fall back to simple requirements. We are not deterministic anyway on this platform so it's fine.
+python3 -m pip install -r ./contrib/requirements/requirements-hw.txt --user || fail "Could not install hardware wallet requirements"
 
 info "Building $PACKAGE..."
 python3 setup.py install --user > /dev/null || fail "Could not build $PACKAGE"
